server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 100MB

minio:
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: minio123
  bucket: platformfiles
